/*  MY NAME=JACOB R KERSTETTER MY ID=JRK154
		
		CORRECT OUTPUT 5 PTS	 CORRECT EXPLANATION 2 POINTS
--------------------------------------------------------------------------
MYSTERY #1:  (1) 951413	             (2) REVERSES THE ORDER OF THE NUMBER INPUT
MYSTERY #2:  (1) 23	                 (2) ADDS THE DIGITS IN REVERSE
MYSTERY #3:  (1) 23	                 (2) ADD THE ELEMENTS OF THE ARRAY IN REVERSE ORDER
MYSTERY #4:  (1) RETURNED FALSE	     (2) ARR[0] = 3 > 1 = ARRAY[0+1] RETURNS FALSE IMMEDIATELY
MYSTERY #5:  (1) 5 4 3 2 1     	     (2) PRINTS THE PARAMETER + SPACE REPEATEDEDLY, SUBTRACTING 1 EACH TIME UNTIL 0
MYSTERY #6:  (1) 1 2 3 4 5	         (2) PRINTS 1 THROUGH 5 BECAUSE PRINT FOLLOWS RECURSIVE METHOD CALL
MYSTERY #7:  (1) 5 4 3 2 1 1 2 3 4 5 (2) PRINTS 5 THROUGH 1 AND THEN 1 THROUGH 5
*/